#!/usr/bin/env python3
"""
MANUAL TESTING GUIDE - Test the Ziyada System workflow
No auto-filling. Manual data entry. Webhook trigger.
"""

print("""
═══════════════════════════════════════════════════════════════════════════════
WORKFLOW TESTING - ZIYADA SYSTEM
═══════════════════════════════════════════════════════════════════════════════

WHAT HAS BEEN FIXED:
✓ Workflow now recognizes column names: trigger_status, status, send_status, 
  workflow_status, switch, active, enabled
✓ For Excel/Sheets input: NO auto-filling - uses only what you provide
✓ For Telegram input: Parsing still works for natural language

═══════════════════════════════════════════════════════════════════════════════
TEST OPTION 1: VIA WEBHOOK (Telegram) - Uses Parsing (OK for Telegram)
═══════════════════════════════════════════════════════════════════════════════

This is the PRIMARY & RECOMMENDED trigger method.

STEP 1: Send company details via Telegram
─ Open Telegram
─ Send message to: @Aliabadi_Ai_Agent_bot (our bot)
─ Type:
  
  اسم الشركة: Ziyada System
  المجال: Software/AI
  الجمهور: Business Leaders
  الرابط: https://ziyada.com
  الموضوع: AI-powered content automation for enterprise

STEP 2: Send trigger command
─ After company details, send in same/new message:
  
  ابدأ التنفيذ
  
  OR
  
  ابدا
  
  OR
  
  generate

EXPECTED RESULT:
─ Within 10-30 seconds, check Google Sheet "ContentResults" tab
─ You'll see a new row with:
  * request_id generated by workflow
  * company_name: "Ziyada System" (from your message)
  * Generated content/article
  * Status: completed

═══════════════════════════════════════════════════════════════════════════════
TEST  OPTION 2: VIA EXCEL/GOOGLE SHEETS - Manual Entry (Recommended for data)
═══════════════════════════════════════════════════════════════════════════════

This is for structured data input.

STEP 1: Open Google Sheet
─ Link: https://docs.google.com/spreadsheets/d/1sUiWimjYYAn_vgVplotMPfKXqI2iuQBzwrAzxgMrW6s/edit
─ Go to tab: "Content Intake"
─ Expected columns:
  A: request_id
  B: company_name
  C: industry
  D: target_audience
  E: company_link
  F: writer_task
  G: trigger_status

STEP 2: Enter data manually (NO AUTO-FILLING)
─ Row 2 (or next empty row):
  A: ZIYADA-TEST-001
  B: Ziyada System          ← YOU MUST ENTER
  C: Software/Tech          ← Or choose from dropdown
  D: Business Leaders       ← Or choose from dropdown
  E: https://ziyada.com     ← YOU MUST ENTER  
  F: Write about AI content automation
  G: start                  ← Or choose 'continue' or 'pause'

IMPORTANT:
✗ DO NOT hardcode fake data
✓ DO enter YOUR company data
✓ trigger_status MUST be exactly: "start" or "continue"

STEP 3: Wait for workflow trigger
─ Polling happens every 1 minute
─ Or manually trigger via webhook (Telegram)
─ Check "ContentResults" tab within 2 minutes

═══════════════════════════════════════════════════════════════════════════════
DEBUGGING: If workflow doesn't trigger
═══════════════════════════════════════════════════════════════════════════════

Check these:

1. COLUMN NAMES (Sheet method):
   ✓ trigger_status exists with value "start" or "continue"
   ✓ company_name is NOT empty
   ✓ company_link is NOT empty
   ✗ NOT named "switch", "active" in row data - only in header!

2. CONTENT RESULTS TAB:
   ✓ Tab name is exactly "ContentResults" (not "resault", not "Results")
   ✓ Can be empty initially

3. WEBHOOK:
   ✓ Telegram bot @Aliabadi_Ai_Agent_bot is online
   ✓ Message format with Arabic labels (company name, sector, etc)

4. WORKFLOW STATUS:
   ✓ n8n workflow is ACTIVE (not paused)
   ✓ All credentials are valid

═══════════════════════════════════════════════════════════════════════════════
EXPECTED BEHAVIOR AFTER FIX
═══════════════════════════════════════════════════════════════════════════════

TELEGRAM PATH (Your message):
Input:  "اسم الشركة: Aeonabaya
         المجال: Fashion
         الجمهور: Women Entrepreneurs  
         الرابط: https://aeonabaya.net
         ابدأ التنفيذ"

Output: Workflow triggers → Generates content → Writes to ContentResults
        NO fake/auto-filled data


SHEET PATH (Your Excel entry):
Input:  company_name="Aeonabaya"
        company_link="https://aeonabaya.net"
        trigger_status="start"

Output: Workflow reads exact values → Generate content using YOUR data
        NO auto-parsing, NO URL extraction from elsewhere


═══════════════════════════════════════════════════════════════════════════════
NEXT STEPS
═══════════════════════════════════════════════════════════════════════════════

1. IMMEDIATE (Try NOW):
   [ ] Send test message via Telegram to @Aliabadi_Ai_Agent_bot
   [ ] Wait 30 seconds
   [ ] Check ContentResults tab for output

2. IF TELEGRAM WORKS:
   [ ] Then setup Excel sheet with dropdown validators
   [ ] Run: python setup_content_intake_sheet.py
   [ ] Add test row with real company data
   [ ] Verify output appears within 2 min

3. IF NEITHER WORKS:
   [ ] Share screenshot of:
     - Your sheet headers and data
     - Error message (if any) from Telegram bot
     - ContentResults tab (empty?)
   [ ] We'll debug further

═══════════════════════════════════════════════════════════════════════════════
KEY REQUIREMENTS (Make sure BEFORE testing!)
═══════════════════════════════════════════════════════════════════════════════

GOOGLE SHEET:
✓ Spreadsheet ID: 1sUiWimjYYAn_vgVplotMPfKXqI2iuQBzwrAzxgMrW6s
✓ Tab 1 "Content Intake" for your data input
✓ Tab 2 "ContentResults" for workflow output

TELEGRAM BOT:
✓ Bot name: @Aliabadi_Ai_Agent_bot
✓ Webhook endpoint: https://n8n.srv953562.hstgr.cloud/webhook/ziyada-blog-ingest
✓ Status: ACTIVE (responding to messages)

N8N WORKFLOW:
✓ ID: C8JWsE3KIoxr1KgO
✓ Name: Ali Content Writer Engine 2026
✓ Status: ACTIVE (not paused)

═══════════════════════════════════════════════════════════════════════════════
""")

# Option to validate setup
print("\nValidating current setup...\n")

import os
import urllib.request
import json

# Check auth
N8N_API_KEY = os.getenv("N8N_API_KEY", "").strip()
if N8N_API_KEY:
    print("✓ N8N_API_KEY environment variable is set")
    
    # Verify webhook is responding
    try:
        webhook_url = "https://n8n.srv953562.hstgr.cloud/webhook/ziyada-blog-ingest"
        test_payload = {
            "update_id": 999999,
            "message": {
                "message_id": 0,
                "date": 0,
                "chat": {"id": 0, "type": "private"},
                "text": "test"
            }
        }
        
        req = urllib.request.Request(
            webhook_url,
            data=json.dumps(test_payload).encode('utf-8'),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        
        response = urllib.request.urlopen(req)
        if response.status == 200:
            print("✓ Webhook endpoint is responding (Status 200)")
        else:
            print(f"⚠ Webhook status: {response.status}")
    except urllib.error.HTTPError as e:
        print(f"⚠ Webhook HTTP error: {e.code}")
    except Exception as e:
        print(f"⚠ Webhook connectivity: {e}")
else:
    print("✗ N8N_API_KEY not set - some advanced tests skipped")

print("\n" + "="*79)
print("Ready to test! Follow TEST OPTION 1 or 2 above.")
print("="*79)
