#!/bin/bash
# Quick Google Docs Import Helper
# This script opens all necessary files for manual import

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║     دليل المبيعات - مساعد الاستيراد إلى Google Docs           ║"
echo "║           Sales Guide - Google Docs Import Helper              ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 الملفات المتاحة:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✓ SALES_GUIDE_MARKDOWN.md      (الأسهل - انسخ + الصق)"
echo "✓ sales_guide_presentation.html (احترافي - استيراد مباشر)"
echo "✓ IMPORT_GUIDE_AR.md           (شرح الخطوات)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 اختر الخطوة:"
echo ""
echo "1) اذهب إلى: https://docs.google.com"
echo "2) اضغط: 'مستند جديد' (أو ⊕)"
echo "3) سماه: 'دليل المبيعات | زيادة سيستم'"
echo "4) افتح هذا الملف من الـ finder:"
echo ""
echo "   📁 /Users/djbiggy/Downloads/Claude\ Code-\ File\ Agents/projects/ziyada-system/outputs/"
echo ""
echo "5) انسخ محتوى SALES_GUIDE_MARKDOWN.md"
echo "6) الصقه في Google Doc"
echo "7) شارك الرابط مع الفريق! ✅"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📞 إذا واجهت مشكلة:"
echo "   اقرأ: IMPORT_GUIDE_AR.md"
echo ""
echo "✅ Done!"
