#!/usr/bin/env bash

# Manual content population guide for Ziyada System Slides
# Open your presentation and follow this slide-by-slide

DECK_LINK="https://docs.google.com/presentation/d/1DtD9wyNWoJrOd1hj3AQXrOBSe2UNwAB70mRTlbtliNo/edit"

echo "🎨 ZIYADA SYSTEM PRESENTATION - MANUAL CONTENT GUIDE"
echo "======================================================"
echo ""
echo "📍 PRESENTATION LINK:"
echo "$DECK_LINK"
echo ""
echo "Copy and paste the content below into each slide."
echo ""
echo "======================================================"
echo ""

# SLIDE 1
echo "SLIDE 1️⃣  - HERO / TITLE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B (Deep Space Navy)"
echo ""
echo "MAIN TITLE (Bold, 60px):"
echo "  Ziyada System"
echo "  نظام زيادة"
echo ""
echo "SUBTITLE (Medium, 32px):"
echo "  Build Once. Scale Logically. Grow Predictably."
echo "  ابنِ مرة واحدة. تكيف بمنطق. نمِ بتنبؤات."
echo ""
echo "BUTTON TEXT (20px, Electric Blue #1F3C88 background):"
echo "  Explore Our System"
echo "  استكشف نظامنا"
echo ""
echo "DESIGN TIPS:"
echo "• Center-align all text"
echo "• Leave 20% margins on sides"
echo "• Use light text color #E6E9F2"
echo "• Add subtle wireframe mesh in background (low opacity)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 2
echo "SLIDE 2️⃣  - WHAT WE BUILD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B"
echo ""
echo "SECTION HEADING (Bold, 48px, Light text):"
echo "  What We Build"
echo "  ما نبنيه"
echo ""
echo "LEFT COLUMN (Regular, 18px):"
echo "━"
echo "We Build Systems."
echo "نبني أنظمة."
echo ""
echo "Not campaigns. Not tools. Not theory."
echo "ليست حملات. ليست أدوات. ليست نظرية."
echo ""
echo "THREE PILLARS (Bold, 22px each, Neural Violet #6B5CFF accent):"
echo "  🔹 Systems"
echo "     Architecture that connects strategy to results"
echo ""
echo "  🔹 Architecture"
echo "     Unified design from customer to cash flow"
echo ""
echo "  🔹 Execution"
echo "     Repeatable operations, predictable growth"
echo ""
echo "RIGHT COLUMN:"
echo "  [INSERT IMAGE: Modern tech/system visualization"
echo "   Image dimensions: 400×300px, rounded 12px corners]"
echo ""
echo "DESIGN TIPS:"
echo "• 2-column layout (text left, image right)"
echo "• Generous padding between columns (30px)"
echo "• Image border: 2px Electric Blue #1F3C88"
echo "• Hover effect on text: Color shift to Soft Neon #2F5CFF"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 3
echo "SLIDE 3️⃣  - WHAT WE'RE NOT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #141D35 (Midnight Blue)"
echo ""
echo "HEADING (Bold, 44px, Light text):"
echo "  Clear Positioning"
echo "  تحديد واضح"
echo ""
echo "TWO-COLUMN LAYOUT:"
echo ""
echo "LEFT - We Are NOT (Red accent #FF5555):"
echo "━━━━━━━━━━━━━━━━━━━━━━━"
echo "❌ A creative agency"
echo "❌ A tool reseller"
echo "❌ A motivational brand"
echo "❌ Another consultancy"
echo ""
echo "We don't do:"
echo "• Campaigns & ads"
echo "• Platform training"
echo "• Inspiration talks"
echo ""
echo "RIGHT - We ARE (Green accent #2FFF7F):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ System builders"
echo "✅ Growth architects"
echo "✅ Execution-driven partners"
echo "✅ Operational operators"
echo ""
echo "We do:"
echo "• Design operating systems"
echo "• Build unified frameworks"
echo "• Drive measurable results"
echo ""
echo "DESIGN TIPS:"
echo "• Each section in card (#141D35 darker background)"
echo "• Red left, Green right (symbolic clarity)"
echo "• 24px font, line height 1.8"
echo "• 40px margin between columns"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 4
echo "SLIDE 4️⃣  - CORE SERVICES (3-CARD GRID)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B"
echo ""
echo "MAIN HEADING (Bold, 44px):"
echo "  What We Do"
echo "  خدماتنا الأساسية"
echo ""
echo "3-COLUMN CARD LAYOUT:"
echo ""
echo "┌─────────────────┬─────────────────┬─────────────────┐"
echo "│   CARD 1        │   CARD 2        │   CARD 3        │"
echo "├─────────────────┼─────────────────┼─────────────────┤"
echo ""
echo "CARD 1:"
echo "━━━━━"
echo "Title: Growth Architecture (Bold, 24px)"
echo "      استراتيجية النمو"
echo ""
echo "subtitle: Strategy + Systems (Secondary text)"
echo ""
echo "[IMAGE: Flowchart or strategy diagram]"
echo ""
echo "Description:"
echo "We design 90-day growth frameworks,"
echo "KPI architectures, and market segmentation."
echo ""
echo "CARD 2:"
echo "━━━━━"
echo "Title: Data Integration (Bold, 24px)"
echo "      تكامل البيانات"
echo ""
echo "Subtitle: Unified Measurement"
echo ""
echo "[IMAGE: Connected nodes / dashboard visual]"
echo ""
echo "Description:"
echo "We unify data from all sources—"
echo "CRM, ads, analytics—into one truth."
echo ""
echo "CARD 3:"
echo "━━━━━"
echo "Title: Operations Automation (Bold, 24px)"
echo "      أتمتة العمليات"
echo ""
echo "Subtitle: Repeatable Execution"
echo ""
echo "[IMAGE: Workflow automation visual]"
echo ""
echo "Description:"
echo "We eliminate manual work. Build workflows"
echo "that scale without adding headcount."
echo ""
echo "CARD DESIGN:"
echo "  • Background: #141D35"
echo "  • Border: 2px Electric Blue #1F3C88"
echo "  • Rounded: 12px"
echo "  • Hover: Border color → Soft Neon #2F5CFF"
echo "  • Padding: 24px"
echo "  • Shadow: Subtle (blur 8px, opacity 0.2)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 5
echo "SLIDE 5️⃣  - WHY ZIYADA (COMPETITIVE ADVANTAGE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #141D35"
echo ""
echo "SPLIT LAYOUT:"
echo ""
echo "LEFT SIDE:"
echo "━━━━━━━━━"
echo "Heading: While Others Optimize Parts (36px, bold)"
echo "        بينما الآخرون يحسنون الأجزاء"
echo ""
echo "[IMAGE: Fragmented system visualization"
echo " - shows scattered tools, disconnected circles]"
echo ""
echo "Sub-text:"
echo "They fix marketing."
echo "Someone else fixes sales."
echo "Data is isolated."
echo "No one owns the whole system."
echo ""
echo ""
echo "RIGHT SIDE:"
echo "━━━━━━━━━"
echo "Heading: Ziyada Designs The Whole System (36px, bold)"
echo "        زيادة تصمم النظام بأكمله"
echo ""
echo "[IMAGE: Integrated system visualization"
echo " - shows connected, unified architecture]"
echo ""
echo "Sub-text:"
echo "Strategy connects to execution."
echo "Marketing feeds sales."
echo "Data flows everywhere."
echo "One system. One truth. Predictable growth."
echo ""
echo "ARROW / CONNECTOR:"
echo "Add large arrow pointing right (or animated divider)"
echo "Color: Gradient Violet→Blue (#6B5CFF → #2F5CFF)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 6
echo "SLIDE 6️⃣  - OUR APPROACH (5-STEP TIMELINE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B"
echo ""
echo "MAIN HEADING (Bold, 44px):"
echo "  Our Approach"
echo "  منهجيتنا"
echo ""
echo "VERTICAL TIMELINE (5 steps):"
echo ""
echo "STEP 1️⃣:"
echo "━━━━━"
echo "Icon: Clipboard / Assessment"
echo "Title: Assess (Bold, 24px)"
echo "      تقييم"
echo ""
echo "Description:"
echo "We audit your current state—tools, data,"
echo "team, bottlenecks. One clear picture."
echo ""
echo "[IMAGE: Audit/analysis visual]"
echo ""
echo "STEP 2️⃣:"
echo "━━━━━"
echo "Icon: Blueprint"
echo "Title: Design (Bold, 24px)"
echo "      تصميم"
echo ""
echo "Description:"
echo "We architect a unified system tailored"
echo "to your business and budget."
echo ""
echo "[IMAGE: Blueprint/architecture visual]"
echo ""
echo "STEP 3️⃣:"
echo "━━━━━"
echo "Icon: Gears/Setting up"
echo "Title: Implement (Bold, 24px)"
echo "      تنفيذ"
echo ""
echo "Description:"
echo "We integrate your tools, move data,\""
echo "set up workflows. Hands-on execution."
echo ""
echo "[IMAGE: Integration/connection visual]"
echo ""
echo "STEP 4️⃣:"
echo "━━━━━"
echo "Icon: Dashboard/Metrics"
echo "Title: Measure (Bold, 24px)"
echo "      قياس"
echo ""
echo "Description:"
echo "We build dashboards and reporting.\""
echo "Now you see what's working."
echo ""
echo "[IMAGE: Dashboard screenshot]"
echo ""
echo "STEP 5️⃣:"
echo "━━━━━"
echo "Icon: Rocket/Growth"
echo "Title: Scale (Bold, 24px)"
echo "      توسع"
echo ""
echo "Description:"
echo "Your system grows predictably."
echo "No more firefighting. Just results."
echo ""
echo "[IMAGE: Growth trajectory chart]"
echo ""
echo "CONNECTING LINES:"
echo "Vertical line connecting all 5 steps (Violet→Blue gradient)"
echo "Arrow animation on scroll (optional)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 7
echo "SLIDE 7️⃣  - WHO WE SERVE (TARGET AUDIENCE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #141D35"
echo ""
echo "MAIN HEADING (Bold, 44px):"
echo "  Who We Work With"
echo "  من نخدم"
echo ""
echo "4-PERSONA GRID:"
echo ""
echo "PERSONA 1:"
echo "━━━━━━━"
echo "Icon: 👔 Founder"
echo ""
echo "Title: Founders (Bold, 22px)"
echo "      المؤسسون"
echo ""
echo "Challenge:"
echo "You're wearing 10 hats. Growth is scattered."
echo ""
echo "What We Solve:"
echo "One system to run everything."
echo "Clear metrics. Clear next steps."
echo ""
echo "PERSONA 2:"
echo "━━━━━━━"
echo "Icon: 🎯 CEO"
echo ""
echo "Title: CEOs / COOs (Bold, 22px)"
echo "      الرؤساء التنفيذيون"
echo ""
echo "Challenge:"
echo "Multiple teams, multiple tools. No clarity."
echo ""
echo "What We Solve:"
echo "Unified operations. One source of truth."
echo "Confident decisions."
echo ""
echo "PERSONA 3:"
echo "━━━━━━━"
echo "Icon: 📈 Growth Leader"
echo ""
echo "Title: Heads of Growth (Bold, 22px)"
echo "      قادة النمو"
echo ""
echo "Challenge:"
echo "You're hitting walls. Can't scale predictably."
echo ""
echo "What We Solve:"
echo "Proven frameworks. Repeatable playbooks."
echo "Sustainable growth."
echo ""
echo "PERSONA 4:"
echo "━━━━━━━"
echo "Icon: 💰 Revenue Leader"
echo ""
echo "Title: Revenue Leaders (Bold, 22px)"
echo "      قادة الإيرادات"
echo ""
echo "Challenge:"
echo "Data silos. Slow decisions. Cost control?"
echo ""
echo "What We Solve:"
echo "Real-time visibility. Fast pivots. ROI clarity."
echo ""
echo "CARD DESIGN:"
echo "  • Each persona in own card (#141D35 or #171C2B)"
echo "  • Border: Electric Blue #1F3C88"
echo "  • Icon: Large (48×48px)"
echo "  • Hover: Subtle shadow increase"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 8
echo "SLIDE 8️⃣  - OUR VALUES (4-BOX GRID)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B"
echo ""
echo "MAIN HEADING (Bold, 44px):"
echo "  How We Work"
echo "  كيفية عملنا"
echo ""
echo "2×2 VALUE GRID:"
echo ""
echo "BOX 1 (Top-Left):"
echo "━━━━━━━━━━━━━"
echo "Accent bar: Neural Violet #6B5CFF"
echo ""
echo "Title: Clarity > Noise (Bold, 26px)"
echo "      الوضوح > الضوضاء"
echo ""
echo "Description:"
echo "No jargon. No buzzwords."
echo "We talk like operators, not marketers."
echo ""
echo "BOX 2 (Top-Right):"
echo "━━━━━━━━━━━━━"
echo "Accent bar: Electric Blue #1F3C88"
echo ""
echo "Title: Structure > Trends (Bold, 26px)"
echo "      البنية > الاتجاهات"
echo ""
echo "Description:"
echo "Systems first. Hype never."
echo "Lasting frameworks, not quick fixes."
echo ""
echo "BOX 3 (Bottom-Left):"
echo "━━━━━━━━━━━━━━"
echo "Accent bar: Soft Neon #2F5CFF"
echo ""
echo "Title: Measurement > Promises (Bold, 26px)"
echo "      القياس > الوعود"
echo ""
echo "Description:"
echo "Data-driven. Results-focused."
echo "Prove everything."
echo ""
echo "BOX 4 (Bottom-Right):"
echo "━━━━━━━━━━━━━"
echo "Accent bar: System Indigo #4A6CFF"
echo ""
echo "Title: Execution > Theory (Bold, 26px)"
echo "      التنفيذ > النظرية"
echo ""
echo "Description:"
echo "Implementation is everything."
echo "We build. We don't just consult."
echo ""
echo "BOX DESIGN:"
echo "  • Background: #141D35"
echo "  • Top accent: 4px solid (rotating colors)"
echo "  • Rounded: 12px"
echo "  • Padding: 28px"
echo "  • Card shadow: Medium (blur 12px)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 9
echo "SLIDE 9️⃣  - SOCIAL PROOF / CASE STUDY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #141D35"
echo ""
echo "FEATURED CARD:"
echo "━━━━━━━━━━━━"
echo "[Client Logo - e.g., TechCo 2024]"
echo ""
echo "BIG RESULT (Bold, 48px, Gradient Violet→Blue):"
echo "  3× Growth"
echo "  نمو ثلاثي"
echo ""
echo "SECONDARY METRIC (Bold, 28px):"
echo "  50% Cost Reduction"
echo "  توفير 50%"
echo ""
echo "QUOTE (Italic, 18px, Secondary text):"
echo '  \"They transformed our scattered efforts'
echo '   into a unified system. Now we can'
echo '   forecast and scale predictably.\"'
echo ""
echo "  \"lقد حولوا جهودنا المتناثرة إلى نظام'"
echo '  موحد. الآن يمكننا التنبؤ والتوسع بثقة.\"'
echo ""
echo "ATTRIBUTION (12px, Muted):"
echo "  CEO / Co-Founder, [Company Name]"
echo "  Saudi Arabia"
echo ""
echo "DESIGN TIPS:"
echo "  • Centered layout"
echo "  • Generous white space"
echo "  • Gradient background on big metric"
echo "  • Client logo (100px wide)"
echo "  • Border: 2px Electric Blue"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 10
echo "SLIDE 🔟 - CALL TO ACTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #171C2B"
echo ""
echo "CENTERED DARK CARD:"
echo "━━━━━━━━━━━━━━━━"
echo "Background: #141D35"
echo "Border: 3px Gradient (Violet #6B5CFF → Blue #2F5CFF)"
echo "Rounded: 16px"
echo "Padding: 50px"
echo ""
echo "MAIN HEADLINE (Bold, 40px):"
echo "  Ready to Build Your Growth System?"
echo "  هل أنت مستعد لبناء نظام نموك؟"
echo ""
echo "SUBHEADING (Medium, 20px, Secondary text):"
echo "  Start with a free strategic system audit."
echo "  ابدأ بفحص نظام استراتيجي مجاني."
echo ""
echo "PRIMARY CTA BUTTON:"
echo "━━━━━━━━━━━━━━━━━"
echo "Text: Schedule Your Audit"
echo "      احجز فحصك"
echo "Background: Electric Blue #1F3C88"
echo "Hover: Soft Neon #2F5CFF"
echo "Text Color: Light #E6E9F2"
echo "Padding: 16px 36px"
echo "Font: Bold 18px"
echo "Rounded: 8px"
echo ""
echo "SECONDARY TEXT (12px, Muted, below button):"
echo "  No credit card required. Takes 15 minutes."
echo ""
echo "DESIGN ANIMATION:"
echo "  • Subtle pulse on border (1s cycle)"
echo "  • Button hover: scale 1.05"
echo "  • Fade-in on view"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# SLIDE 11
echo "SLIDE 1️⃣1️⃣ - FOOTER / CONTACT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "BACKGROUND COLOR: #141D35 (Midnight Blue)"
echo ""
echo "LAYOUT: 3-column footer centered"
echo ""
echo "COLUMN 1 - BRAND:"
echo "━━━━━━━━━━━━━"
echo "[Logo - Ziyada System, 60px width]"
echo ""
echo "Ziyada System"
echo "نظام زيادة"
echo ""
echo "Growth Systems & Revenue Architecture"
echo "أنظمة النمو وهندسة الإيرادات"
echo ""
echo "COLUMN 2 - CONTACT:"
echo "━━━━━━━━━━━━━━━━"
echo "Email:"
echo "contact@ziyadasystem.com"
echo ""
echo "Phone:"
echo "+966 (Saudi Arabia)"
echo ""
echo "Location:"
echo "🇸🇦 Riyadh, Saudi Arabia"
echo ""
echo "COLUMN 3 - SOCIAL & LINKS:"
echo "━━━━━━━━━━━━━━━━━━━━━━"
echo "Follow Us:"
echo "[LinkedIn] [Twitter] [Instagram]"
echo ""
echo "Quick Links:"
echo "• Services"
echo "• Blog"
echo "• Privacy Policy"
echo "• Terms of Use"
echo ""
echo "BOTTOM LINE (Small, Muted):"
echo "━━━━━━━━━━━━━━━━"
echo "© 2026 Ziyada System. All Rights Reserved."
echo "Made with intent. Built for scale."
echo ""
echo "DESIGN:"
echo "  • Each column: 30% width"
echo "  • Generous padding (40px)"
echo "  • Text: Secondary color #9AA3B2"
echo "  • Links: Light text, hover → Electric Blue"
echo "  • Separator lines (1px, muted)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Summary
echo ""
echo "════════════════════════════════════════════════════"
echo "✅ MANUAL CONTENT ENTRY COMPLETE"
echo "════════════════════════════════════════════════════"
echo ""
echo "📊 PRESENTATION DASHBOARD:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Status: Structure Created ✅  "
echo "Content: Ready to Add 📝"
echo "Images: Sourcing Required 🖼️"
echo "Animations: Optional ✨"
echo ""
echo "🎨 KEY COLORS TO REMEMBER:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "#171C2B  → Deep Space Navy (primary bg)"
echo "#141D35  → Midnight Blue (cards)"
echo "#1F3C88  → Electric System Blue (accent)"
echo "#2F5CFF  → Soft Neon Blue (active)"
echo "#6B5CFF  → Neural Violet (highlights)"
echo "#E6E9F2  → Light Text"
echo "#9AA3B2  → Secondary Text"
echo ""
echo "🖼️  IMAGES TO FIND/CREATE:"
echo "━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Wireframe mesh (hero background)"
echo "2. System architecture diagram"
echo "3. Team photo (modern office)"
echo "4. Fragmented vs unified visual"
echo "5. Dashboard/metrics screenshot"
echo "6. Growth trajectory chart"
echo "7. Data flow / connected nodes"
echo "8. Client testimonial (optional)"
echo ""
echo "Sources: Unsplash.com | Pexels.com | Custom Figma"
echo ""
echo "💡 NEXT STEPS:"
echo "━━━━━━━━━━━"
echo "1. Open presentation: $DECK_LINK"
echo "2. Go slide by slide"
echo "3. Copy/paste content from above"
echo "4. Insert images"
echo "5. Apply colors & typography"
echo "6. Add animations (smooth transitions)"
echo "7. Test bilingual (EN/AR)"
echo "8. Share with team"
echo ""
echo "════════════════════════════════════════════════════"
